# Generated by Django 2.2.6 on 2019-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('price', models.IntegerField()),
                ('expected_time', models.DurationField()),
                ('take_out_available', models.BooleanField(default=False)),
                ('option_json', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('information', models.TextField(max_length=200)),
            ],
        ),
    ]
