# Generated by Django 2.2.6 on 2019-11-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='option',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
