# Generated by Django 2.2.6 on 2019-11-05 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20191105_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
