# Generated by Django 2.2.6 on 2019-11-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20191105_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
