# Generated by Django 2.2.6 on 2019-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20191105_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='option',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
