# Generated by Django 2.2.6 on 2019-11-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20191106_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
