# Generated by Django 2.2.6 on 2019-11-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20191114_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='altitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
    ]
