# Generated by Django 2.2.6 on 2019-11-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_auto_20191115_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeprofile',
            old_name='altitude',
            new_name='longitude',
        ),
    ]
