# Generated by Django 3.0 on 2019-12-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_auto_20191115_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
