# Generated by Django 3.0 on 2019-12-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_auto_20191209_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
