# Generated by Django 3.0 on 2019-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_auto_20191209_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
