# Generated by Django 2.2.6 on 2019-11-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Menu'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Store.StoreProfile'),
        ),
    ]
