# Generated by Django 2.2.6 on 2019-11-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='option',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
