# Generated by Django 2.2.6 on 2019-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20191104_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='option',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='request',
            field=models.CharField(max_length=100),
        ),
    ]
