# Generated by Django 2.2.6 on 2019-11-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20191106_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
