# Generated by Django 2.2.6 on 2019-11-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_ordermenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='option',
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='option',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
