# Generated by Django 2.2.6 on 2019-11-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_auto_20191124_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
