# Generated by Django 2.2.6 on 2019-11-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_auto_20191124_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='option',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
