# Generated by Django 3.0 on 2019-12-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_auto_20191125_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_time',
            field=models.DateTimeField(null=True),
        ),
    ]
