# Generated by Django 3.0 on 2019-12-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_auto_20191115_1035'),
        ('Order', '0013_order_expected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Store.StoreProfile'),
        ),
    ]
