# Generated by Django 3.0 on 2019-12-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_auto_20191208_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_time',
            field=models.DurationField(null=True),
        ),
    ]
