# Generated by Django 3.0 on 2019-12-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20191106_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
