# Generated by Django 3.0 on 2019-12-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_remove_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(null=True, upload_to='user/%Y/%m/%d'),
        ),
    ]
